"""Plain text and HTML body preparation for HIVE forensic output.

Cleans and normalises parser-extracted body content for safe writing to
body.txt and body.html.txt. HTML is never rendered or executed — only
stored with a safety header for analyst review.
"""

from __future__ import annotations

import logging
import re

from hive.parser.common import ParsedEmail

logger = logging.getLogger(__name__)

# Entire <style>...</style> blocks including content
_STYLE_BLOCK_RE = re.compile(r"<style[^>]*>.*?</style>", re.IGNORECASE | re.DOTALL)

# Entire <script>...</script> blocks including content
_SCRIPT_BLOCK_RE = re.compile(r"<script[^>]*>.*?</script>", re.IGNORECASE | re.DOTALL)

# Individual HTML tags
_TAG_RE = re.compile(r"<[^>]+>")

# Runs of spaces or tabs within a single line
_INLINE_WHITESPACE_RE = re.compile(r"[ \t]+")

# Three or more consecutive newlines
_EXCESS_NEWLINES_RE = re.compile(r"\n{3,}")

_HTML_SAFETY_HEADER = """<!--
  HIVE - RAW EMAIL HTML BODY
  DO NOT OPEN THIS FILE IN A BROWSER
  DO NOT CLICK ANY LINKS
  Generated by HIVE for forensic analysis only
-->"""

_PLAIN_FROM_HTML_NOTICE = "[Plain text body not available — extracted from HTML]"
_NO_BODY_TEXT = "[No body content available]"
_NO_HTML_BODY = "[No HTML body available]"


def _strip_html_tags(html: str) -> str:
    """Remove HTML tags and discard style/script block content.

    Uses regex only — no third-party HTML parsers.
    """
    try:
        text = _STYLE_BLOCK_RE.sub("", html)
        text = _SCRIPT_BLOCK_RE.sub("", text)
        return _TAG_RE.sub("", text)
    except Exception:
        logger.exception("Failed to strip HTML tags")
        return html


def _decode_html_entities(text: str) -> str:
    """Replace common HTML entities with their Unicode equivalents."""
    try:
        replacements = (
            ("&amp;", "&"),
            ("&lt;", "<"),
            ("&gt;", ">"),
            ("&quot;", '"'),
            ("&apos;", "'"),
            ("&#160;", " "),
            ("&nbsp;", " "),
        )
        for entity, char in replacements:
            text = text.replace(entity, char)
        return text
    except Exception:
        logger.exception("Failed to decode HTML entities")
        return text


def _collapse_whitespace(text: str) -> str:
    """Normalise line endings and collapse excessive whitespace."""
    try:
        text = text.replace("\r\n", "\n").replace("\r", "\n")
        lines = [_INLINE_WHITESPACE_RE.sub(" ", line) for line in text.split("\n")]
        text = "\n".join(lines)
        text = _EXCESS_NEWLINES_RE.sub("\n\n", text)
        return text.strip()
    except Exception:
        logger.exception("Failed to collapse whitespace")
        return text


def _html_to_plain_fallback(html: str) -> str:
    """Convert HTML body content into a plain-text fallback string."""
    text = _strip_html_tags(html)
    text = _decode_html_entities(text)
    text = _collapse_whitespace(text)
    return f"{_PLAIN_FROM_HTML_NOTICE}\n{text}"


def get_body_txt(email: ParsedEmail) -> str:
    """Return cleaned plain-text body content for body.txt.

    Uses the parser-provided plain body when available. Falls back to a
    regex-based HTML-to-text conversion when only HTML is present.

    Args:
        email: Parsed email with body_plain and/or body_html fields.

    Returns:
        Plain-text body content ready for writing to disk.
    """
    try:
        if email.body_plain and email.body_plain.strip():
            return email.body_plain

        if email.body_html and email.body_html.strip():
            return _html_to_plain_fallback(email.body_html)

        return _NO_BODY_TEXT
    except Exception:
        logger.exception("Failed to prepare body.txt content")
        return _NO_BODY_TEXT


def get_body_html_txt(email: ParsedEmail) -> str:
    """Return raw HTML body content for body.html.txt.

    Prepends a safety comment block before the unmodified HTML when a
    body is present. The file must never be opened in a browser.

    Args:
        email: Parsed email with an optional body_html field.

    Returns:
        Safety header plus raw HTML, or a placeholder when absent.
    """
    try:
        if email.body_html and email.body_html.strip():
            return f"{_HTML_SAFETY_HEADER}\n{email.body_html}"

        return _NO_HTML_BODY
    except Exception:
        logger.exception("Failed to prepare body.html.txt content")
        return _NO_HTML_BODY
